GET   http://localhost:7000/users/155







###




POST  http://localhost:7000/users
 Content-Type: application/json

{
  "last_name": "mohamed", "first_name":"mohamed","password": "password"
}

###
GET   http://localhost:7000/users
Content-Type:application/json

###

GET  http://localhost:7000/orderdProducts




